[project]
name = "tinytuta2mqtt"
version = "1.3.4"
description = "Service to interact with Tuya WiFi devices via MQTT broker"
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
  "paho-mqtt>=2.1.0",
  "tinytuya>=1.16.0",
  "python-dotenv>=1.1.0"
]